---
title: "Urban_Coyotes"
author: "Jonathan Farr"
date: "1/15/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Reading in Packages
```{r}
library(here)
library(tidyverse)
library(raster)
library(sp)
library(PBSmapping)

library(arcgisbinding)
arc.check_product()


```


Data Reading
```{r}
data = read.csv("Data/JJFCoyotesMarch82021.csv")

data = data %>% 
  mutate(Date = as.Date(Date, format = "%m/%d/%Y")) %>%
  mutate(covid = ifelse(Date > "2020-04-01", "Y", "N"), 
         CoyoteResponse = as.ordered(CoyoteResponse), 
         HumanPerception = as.ordered(HumanPerception),
         MO100m = ag100m + oNm100m,
         MO200m = ag200m + oNm200m,
         MO400m = ag400m + oNm400m,
         MO800m = ag800m + oNm800m,
         MO1600m = ag1600m + oNm1600m)%>%
  filter(Date > "2010-12-31")
```


Looking into ordinal regression models
```{r}
library(ordinal)
response = data %>%
  filter(CoyoteResponse != "Unknown", CoyoteResponse != 0)


response_full = clm(CoyoteResponse ~ RoadDistDecay + MO200m  + nat200m + om200m + com200m + res200m + Season + as.factor(Year), data = response, na.action="na.fail")

summary(response_full)


dredge_response <- MuMIn::dredge(response_full) 
view(dredge_response)
dredge_results_response <- MuMIn::model.avg(dredge_response, subset=delta < 2)
summary(dredge_results_response)

response_results <- data.frame(
  conf_2.5 = confint(dredge_results_response, level=0.95)[,1],
  odds = coef(dredge_results_response),
  conf_97.5 = confint(dredge_results_response, level=0.95)[,2]
)


response_results

response_results = response_results[-c(1:8),]
response_results$label = rownames(response_results)

ggplot(response_results, aes(x=label, y=odds)) + 
  ylab("\nLog Odds of Change in Ordinal Scale (99% CI)") + xlab("\nSpatial Predictor") +
  theme_classic()+
  theme(
    axis.text.x=element_text(size=15, family="Times"),
    axis.text.y=element_text(size=15, family="Times"), 
    axis.title.y=element_text(size=18, face="bold", family="Times"),
    axis.title.x=element_text(size=18, face="bold", family="Times"),
    legend.title=element_text(size=24, face="bold", family="Times"), 
    legend.text=element_text(size=22, family="Times"), 
    legend.position= "none")+ 
  geom_hline(yintercept=0, linetype=2)+
  geom_errorbar(aes(x=label, ymin=conf_2.5, ymax=conf_97.5), width=0, size=1, position=position_dodge(0.3)) + 
  theme(panel.spacing.x=unit(0, "lines"),
        strip.text=element_text(size=20, face="bold", family="Times"),
        strip.placement = "outside", 
        panel.border = element_rect(fill=NA, color="black"),
        axis.text.x = element_text(angle = 90))   


```

Reading in a raster file 
```{r}
Com200m = raster("Data/GIS_Layers/LandCover200m/Com200m.tif")

plot(Com200m)
Com200m_prop = Com200m/1257
plot(Com200m_prop)
Com200m

```

Reading in spatial points
```{r}
Coyotes_arc = arc.select(arc.open("Data/GIS_Layers/UrbanCoyotesArcGIS/UrbanCoyotes.gdb/JJFCoyotesMarch82021_Projected"))
class(Coyotes_arc)

Coyotes.sp <- arc.data2sp(Coyotes_arc)

Coyotes.sp@coords
Coyotes.sp@proj4string

Coyotes.df = data.frame(Coyotes.sp)
str(Coyotes.df)


```

Playing with basic spatial analysis
```{r}
projection(Coyotes.sp)
projection(Com200m_prop)


image(myCom200m, col = terrain.colors(100), asp = 1, xlim =  bbox(Com200m)[1,], ylim =  bbox(Com200m)[2,],
            main = "Com200m")
points(Coyotes.sp, col="black", lwd=1)

myCom200m <- crop(Com200m_prop, extent(Coyotes.sp))


Coyotes.sp$Com200m_NEW = raster::extract(Com200m_prop, Coyotes.sp)

str(Coyotes.sp)

new  = data.frame(Coyotes.sp$Com200m_NEW, Coyotes.sp$com200m)

head(new)
```


